## Numpy Array and Basics

learn about numpy with chai aur code


In [1]:
import numpy as np

creating Array from List


In [8]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print(type(arr_1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])    
print(arr_2d)
print(type(arr_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


## List vs Numpy Array


In [10]:
py_list = [1,2,3,4,5]
print("Python list multiplication: ", py_list*2)

np_arr = np.array([1,2,3,4,5])
print("Numpy array multiplication: ", np_arr*2)

Python list multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication:  [ 2  4  6  8 10]


In [2]:
import time

start = time.time()
py_list = [i * 2 for i in range(100000000)]
print(time.time() - start)

start = time.time()
np_arr = np.arange(100000000) * 2
print(time.time() - start)

6.893060922622681
1.8519461154937744


### Creating array from scratch


In [ ]:
zeros = np.zeros((3,3))
# print(zeros)

ones = np.ones((3,3))
# print(ones)

# empty = np.empty((3,3))
# print(empty)

# full = np.full((1000,1000),12)
# print(full)

ranodm = np.random.random((3,3))
# print(ranodm)

seq = np.arange(0,10,2)
# print(seq)



[0 2 4 6 8]


### Vector, Matrix, Tensor


In [ ]:
vector = np.array([1,2,3,4,5,6,7,8,9])
# print(vector)
# print(vector[0])
# print(vector[1])

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
# print(matrix)

tensor = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])
print(tensor[0][0][0])



[1 2 3 4 5 6 7 8 9]
1


## Array Properties


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
shape = arr.shape
print(f"shape: {shape}")
print(f"dimension: {arr.ndim}")
print(f"datatype: {arr.dtype}")
print(f"size: {arr.size}")

shape: (3, 3)
dimension: 2
datatype: int64
size: 9


## Array Reshaping


In [17]:
arr = np.arange(12)
# print(arr)

reshaped = arr.reshape((3,4))
print(reshaped)

flattend = reshaped.flatten()
print(flattend)

# ravel (returns a view ,instead of a copy)
raveled = reshaped.ravel()
print(raveled)

# Transpose
transpose = reshaped.T
print(transpose)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## NumPy Array Operations


In [3]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
# print(f"basic slicing: {arr[0:3]}")
# print(f"with step: {arr[0:9:2]}")

arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9,]])

# print(f"Specific element: {arr_2d[1,2]}")
# print(f"Entire Row {arr_2d[1]}")
# print(f"Entire column {arr_2d[:,1]}")



Entire Row [4 5 6]
Entire Row [2 5 8]


## sorting


In [ ]:
unsorted = np.array([2,4,546,324,4555,234324,3244])
# print(f"sorted array {np.sort(unsorted)}")

arr_2d_unsorted = np.array([[3,1],[1,4],[2,3]])

# print(f"Sorted 2D Array By Column\n {np.sort(arr_2d_unsorted,axis=0)}")
# print(f"Sorted 2D Array By row\n {np.sort(arr_2d_unsorted,axis=1)}")





Sorted 2D Array By row
 [[1 3]
 [1 4]
 [2 3]]


# Filter


In [18]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
# print(f"Max: {numbers.max()}")

even_number = numbers[numbers % 2 == 0]
print("Even numbers",even_number)



Even numbers [2 4 6 8]


# Filter With Mask


In [20]:
mask = numbers > 5
print("Number greater than 5",numbers[mask])

Number greater than 5 [6 7 8 9]


## Fancy INdexing vs np.array()


In [ ]:
indices = [0,2,4]
# print("Selected numbers",numbers[indices])

where_result = np.where(numbers > 5)
# print("Where result",numbers[where_result])

Where result [6 7 8 9]


In [ ]:
# condition_array = np.where(numbers > 5, numbers*2 ,numbers )
condition_array = np.where(numbers > 5, "true","false" )
# print(condition_array)



[ 1  2  3  4  5 12 14 16 18]


## Adding and Removing Data


In [70]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
# print(combined)
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibiliy


In [73]:
a = np.array([1,2,3])
b = np.array([4,5,6,])
c = np.array([7,8,9])

print(f"Compatibility Shape: {a.shape == b.shape}")


Compatibility Shape: True


In [78]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])

with_new_row = np.vstack((original,new_row))
# print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)


[[1 2 7]
 [3 4 8]]
