## Numpy Array and Basics

learn about numpy with chai aur code


In [2]:
import numpy as np

creating Array from List


In [8]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print(type(arr_1d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])    
print(arr_2d)
print(type(arr_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


## List vs Numpy Array


In [10]:
py_list = [1,2,3,4,5]
print("Python list multiplication: ", py_list*2)

np_arr = np.array([1,2,3,4,5])
print("Numpy array multiplication: ", np_arr*2)

Python list multiplication:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication:  [ 2  4  6  8 10]


In [2]:
import time

start = time.time()
py_list = [i * 2 for i in range(100000000)]
print(time.time() - start)

start = time.time()
np_arr = np.arange(100000000) * 2
print(time.time() - start)

6.893060922622681
1.8519461154937744


### Creating array from scratch


In [ ]:
zeros = np.zeros((3,3))
# print(zeros)

ones = np.ones((3,3))
# print(ones)

# empty = np.empty((3,3))
# print(empty)

# full = np.full((1000,1000),12)
# print(full)

ranodm = np.random.random((3,3))
# print(ranodm)

seq = np.arange(0,10,2)
# print(seq)



[0 2 4 6 8]


### Vector, Matrix, Tensor


In [ ]:
vector = np.array([1,2,3,4,5,6,7,8,9])
# print(vector)
# print(vector[0])
# print(vector[1])

matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
# print(matrix)

tensor = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [19,20,21],
        [22,23,24],
        [25,26,27]
    ]
])
print(tensor[0][0][0])



[1 2 3 4 5 6 7 8 9]
1


## Array Properties


In [11]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
shape = arr.shape
print(f"shape: {shape}")
print(f"dimension: {arr.ndim}")
print(f"datatype: {arr.dtype}")
print(f"size: {arr.size}")

shape: (3, 3)
dimension: 2
datatype: int64
size: 9


## Array Reshaping

In [17]:
arr = np.arange(12)
# print(arr)

reshaped = arr.reshape((3,4))
print(reshaped)

flattend = reshaped.flatten()
print(flattend)

# ravel (returns a view ,instead of a copy)
raveled = reshaped.ravel()
print(raveled)

# Transpose
transpose = reshaped.T
print(transpose)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
