## numpy chai aur code

In [2]:
import numpy as np


### creating array from list

In [6]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### list vs numpy array

In [4]:
py_list = [1,2,3]
print("python list multiplication: ", py_list*3)
np_arr = np.array([1,2,3])# element wise multiplication
print("numpy array multiplication: ", np_arr*3)

import time

start = time.time()
np_arr = np.arange(100000000)*2
print("Numpy array operation time: ",time.time()-start)
start = time.time()
# py_list = [i*2 for i in range(10000000000)]
print("List operation time: ",time.time()-start)

python list multiplication:  [1, 2, 3, 1, 2, 3, 1, 2, 3]
numpy array multiplication:  [3 6 9]
Numpy array operation time:  0.7129437923431396
List operation time:  2.8371810913085938e-05


creating array from scratch


In [13]:
zeros = np.zeros((3,4))
print(zeros)
ones = np.ones((2,3))
print(ones)
full = np.full((2,2), 5)
print(full)
random = np.random.random((2,2))
print(random)

sequence = np.arange(0,10,2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]]
[[0.5855468  0.67316394]
 [0.09025314 0.33962029]]
[0 2 4 6 8]


### Vector ,Matrix and Tensor

In [3]:
vector= np.array([1,2,3,4,5])
print(vector)
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(tensor)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [4]:
arr = np.array([1,2,3,4,5])
print(arr.shape)

(5,)
